In [0]:
# Libraries for data processing
import pandas as pd
import numpy as np
import matplotlib.pyplot as ptl

In [0]:
# Loading data from  table using spark
df = spark.table("retail.default.retail_sales_dataset")

In [0]:

rs = df.toPandas()

understanding the data

In [0]:
rs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [0]:
# Generating descriptive statistics such as mean, min, max, and quartiles for numerical columns
rs.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [0]:
# Listing all column names in the dataset
rs.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

In [0]:
# Displaying the dataset
display(rs)

Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
10,2023-10-07,CUST010,Female,52,Clothing,4,50,200
11,2023-02-14,CUST011,Male,23,Clothing,2,50,100
12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,2023-01-17,CUST014,Male,64,Clothing,4,30,120
15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
16,2023-02-17,CUST016,Male,19,Clothing,3,500,1500
17,2023-04-22,CUST017,Female,27,Clothing,4,25,100
18,2023-04-30,CUST018,Female,47,Electronics,2,25,50
19,2023-09-16,CUST019,Female,62,Clothing,2,25,50
20,2023-11-05,CUST020,Male,22,Clothing,3,300,900
21,2023-01-14,CUST021,Female,50,Beauty,1,500,500
22,2023-10-15,CUST022,Male,18,Clothing,2,50,100
23,2023-04-12,CUST023,Female,35,Clothing,4,30,120
24,2023-11-29,CUST024,Female,49,Clothing,1,300,300
25,2023-12-26,CUST025,Female,64,Beauty,1,50,50
26,2023-10-07,CUST026,Female,28,Electronics,2,500,1000
27,2023-08-03,CUST027,Female,38,Beauty,2,25,50
28,2023-04-23,CUST028,Female,43,Beauty,1,500,500
29,2023-08-18,CUST029,Female,42,Electronics,1,30,30
30,2023-10-29,CUST030,Female,39,Beauty,3,300,900
31,2023-05-23,CUST031,Male,44,Electronics,4,300,1200
32,2023-01-04,CUST032,Male,30,Beauty,3,30,90
33,2023-03-23,CUST033,Female,50,Electronics,2,50,100
34,2023-12-24,CUST034,Female,51,Clothing,3,50,150
35,2023-08-05,CUST035,Female,58,Beauty,3,300,900
36,2023-06-24,CUST036,Male,52,Beauty,3,300,900
37,2023-05-23,CUST037,Female,18,Beauty,3,25,75
38,2023-03-21,CUST038,Male,38,Beauty,4,50,200
39,2023-04-21,CUST039,Male,23,Clothing,4,30,120
40,2023-06-22,CUST040,Male,45,Beauty,1,50,50
41,2023-02-22,CUST041,Male,34,Clothing,2,25,50
42,2023-02-17,CUST042,Male,22,Clothing,3,300,900
43,2023-07-14,CUST043,Female,48,Clothing,1,300,300
44,2023-02-19,CUST044,Female,22,Clothing,1,25,25
45,2023-07-03,CUST045,Female,55,Electronics,1,30,30
46,2023-06-26,CUST046,Female,20,Electronics,4,300,1200
47,2023-11-06,CUST047,Female,40,Beauty,3,500,1500
48,2023-05-16,CUST048,Male,54,Electronics,3,300,900
49,2023-01-23,CUST049,Female,54,Electronics,2,500,1000
50,2023-08-24,CUST050,Female,27,Beauty,3,25,75
51,2023-10-02,CUST051,Male,27,Beauty,3,25,75
52,2023-03-05,CUST052,Female,36,Beauty,1,300,300
53,2023-07-13,CUST053,Male,34,Electronics,2,50,100
54,2023-02-10,CUST054,Female,38,Electronics,3,500,1500
55,2023-10-10,CUST055,Male,31,Beauty,4,30,120
56,2023-05-31,CUST056,Female,26,Clothing,3,300,900
57,2023-11-18,CUST057,Female,63,Beauty,1,30,30
58,2023-11-13,CUST058,Male,18,Clothing,4,300,1200
59,2023-07-05,CUST059,Male,62,Clothing,1,50,50
60,2023-10-23,CUST060,Male,30,Beauty,3,50,150
61,2023-04-09,CUST061,Male,21,Beauty,4,50,200
62,2023-12-27,CUST062,Male,18,Beauty,2,50,100
63,2023-02-05,CUST063,Male,57,Electronics,2,25,50
64,2023-01-24,CUST064,Male,49,Clothing,4,25,100
65,2023-12-05,CUST065,Male,51,Electronics,4,500,2000
66,2023-04-27,CUST066,Female,45,Electronics,1,30,30
67,2023-05-29,CUST067,Female,48,Beauty,4,300,1200
68,2023-02-10,CUST068,Male,25,Electronics,1,300,300
69,2023-04-30,CUST069,Female,56,Beauty,3,25,75
70,2023-02-21,CUST070,Female,43,Clothing,1,300,300
71,2023-07-14,CUST071,Female,51,Beauty,4,25,100
72,2023-05-23,CUST072,Female,20,Electronics,4,500,2000
73,2023-08-21,CUST073,Male,29,Electronics,3,30,90
74,2023-11-22,CUST074,Female,18,Beauty,4,500,2000
75,2023-07-06,CUST075,Male,61,Beauty,4,50,200
76,2023-03-25,CUST076,Female,22,Electronics,2,50,100
77,2023-07-09,CUST077,Female,47,Clothing,2,50,100
78,2023-07-01,CUST078,Female,47,Clothing,3,500,1500
79,2023-04-18,CUST079,Male,34,Beauty,1,300,300
80,2023-12-10,CUST080,Female,64,Clothing,2,30,60
81,2023-05-17,CUST081,Male,40,Electronics,1,50,50
82,2023-12-26,CUST082,Female,32,Beauty,4,50,200
83,2023-12-16,CUST083,Male,54,Electronics,2,50,100
84,2023-11-28,CUST084,Female,38,Electronics,3,30,90
85,2023-02-06,CUST085,Male,31,Clothing,3,50,150
86,2023-11-08,CUST086,Male,19,Beauty,3,30,90
87,2023-11-22,CUST087,Female,28,Beauty,2,50,100
88,2023-03-29,CUST088,Male,56,Clothing,1,500,500
89,2023-10-01,CUST089,Female,55,Electronics,4,500,2000
90,2023-05-06,CUST090,Female,51,Electronics,1,30,30
91,2023-03-25,CUST091,Female,55,Electronics,1,500,500
92,2023-08-25,CUST092,Female,51,Electronics,4,30,120
93,2023-07-14,CUST093,Female,35,Beauty,4,500,2000
94,2023-05-19,CUST094,Female,47,Beauty,2,500,1000
95,2023-11-24,CUST095,Female,32,Clothing,2,30,60
96,2023-12-19,CUST096,Female,44,Clothing,2,300,600
97,2023-10-13,CUST097,Female,51,Beauty,2,500,1000
98,2023-04-23,CUST098,Female,55,Beauty,2,50,100
99,2023-12-17,CUST099,Female,50,Electronics,4,300,1200
100,2023-06-16,CUST100,Male,41,Electronics,1,30,30
101,2023-01-29,CUST101,Male,32,Clothing,2,300,600
102,2023-04-28,CUST102,Female,47,Beauty,2,25,50
103,2023-01-17,CUST103,Female,59,Clothing,1,25,25
104,2023-06-11,CUST104,Female,34,Beauty,2,500,1000
105,2023-07-25,CUST105,Female,22,Electronics,1,500,500
106,2023-05-18,CUST106,Female,46,Clothing,1,50,50
107,2023-02-03,CUST107,Female,21,Clothing,4,300,1200
108,2023-04-19,CUST108,Female,27,Beauty,3,25,75
109,2023-10-18,CUST109,Female,34,Electronics,4,500,2000
110,2023-06-11,CUST110,Male,27,Clothing,3,300,900
111,2023-04-19,CUST111,Female,34,Electronics,3,500,1500
112,2023-12-02,CUST112,Male,37,Clothing,3,500,1500
113,2023-09-13,CUST113,Female,41,Electronics,2,25,50
114,2023-07-22,CUST114,Female,22,Beauty,4,25,100
115,2023-11-26,CUST115,Male,51,Clothing,3,500,1500
116,2023-08-23,CUST116,Female,23,Clothing,1,30,30
117,2023-03-15,CUST117,Male,19,Electronics,2,500,1000
118,2023-05-16,CUST118,Female,30,Electronics,4,500,2000
119,2023-03-13,CUST119,Female,60,Clothing,3,50,150
120,2023-05-07,CUST120,Male,60,Beauty,1,50,50
121,2023-10-15,CUST121,Female,28,Electronics,4,50,200
122,2023-10-03,CUST122,Male,64,Electronics,4,30,120
123,2023-05-15,CUST123,Female,40,Electronics,2,30,60
124,2023-10-27,CUST124,Male,33,Clothing,4,500,2000
125,2023-08-08,CUST125,Male,48,Clothing,2,50,100
126,2023-10-26,CUST126,Female,28,Clothing,3,30,90
127,2023-07-24,CUST127,Female,33,Clothing,2,25,50
128,2023-07-05,CUST128,Male,25,Beauty,1,500,500
129,2023-04-23,CUST129,Female,21,Beauty,2,300,600
130,2023-03-12,CUST130,Female,57,Clothing,1,500,500
131,2023-09-18,CUST131,Female,21,Beauty,2,300,600
132,2023-09-10,CUST132,Male,42,Electronics,4,50,200
133,2023-02-16,CUST133,Male,20,Electronics,3,300,900
134,2023-01-25,CUST134,Male,49,Electronics,1,50,50
135,2023-02-26,CUST135,Male,20,Clothing,2,25,50
136,2023-03-20,CUST136,Male,44,Electronics,2,300,600
137,2023-11-18,CUST137,Male,46,Beauty,2,500,1000
138,2023-03-23,CUST138,Male,49,Clothing,4,50,200
139,2023-12-15,CUST139,Male,36,Beauty,4,500,2000
140,2023-08-05,CUST140,Male,38,Electronics,1,30,30
141,2023-11-02,CUST141,Female,22,Electronics,1,50,50
142,2023-02-02,CUST142,Male,35,Electronics,4,300,1200
143,2023-07-17,CUST143,Female,45,Clothing,1,50,50
144,2023-07-15,CUST144,Female,59,Beauty,3,500,1500
145,2023-11-02,CUST145,Female,39,Clothing,3,25,75
146,2023-08-28,CUST146,Male,38,Clothing,4,50,200
147,2023-09-28,CUST147,Male,23,Electronics,1,300,300
148,2023-05-09,CUST148,Male,18,Clothing,2,30,60
149,2023-10-11,CUST149,Male,22,Clothing,3,25,75
150,2023-01-06,CUST150,Female,58,Electronics,4,30,120
151,2023-12-15,CUST151,Male,29,Clothing,1,50,50
152,2023-02-28,CUST152,Male,43,Electronics,4,500,2000
153,2023-12-16,CUST153,Male,63,Electronics,2,500,1000
154,2023-10-02,CUST154,Male,51,Electronics,3,300,900
155,2023-05-17,CUST155,Male,31,Electronics,4,500,2000
156,2023-11-25,CUST156,Female,43,Clothing,4,25,100
157,2023-06-24,CUST157,Male,62,Electronics,4,500,2000
158,2023-02-27,CUST158,Female,44,Electronics,2,300,600
159,2023-05-31,CUST159,Male,26,Clothing,4,50,200
160,2023-08-11,CUST160,Female,43,Clothing,2,50,100
161,2023-03-22,CUST161,Male,64,Beauty,2,500,1000
162,2023-08-21,CUST162,Male,39,Clothing,2,30,60
163,2023-01-02,CUST163,Female,64,Clothing,3,50,150
164,2023-05-15,CUST164,Female,47,Beauty,3,500,1500
165,2023-09-14,CUST165,Female,60,Clothing,4,300,1200
166,2023-04-02,CUST166,Male,34,Clothing,4,500,2000
167,2023-09-17,CUST167,Female,43,Clothing,3,50,150
168,2023-02-24,CUST168,Male,53,Clothing,1,300,300
169,2023-11-17,CUST169,Male,18,Beauty,3,500,1500
170,2023-06-02,CUST170,Female,25,Clothing,2,25,50
171,2023-11-24,CUST171,Female,52,Clothing,3,300,900
172,2023-09-17,CUST172,Male,32,Beauty,2,25,50
173,2023-11-08,CUST173,Male,64,Electronics,4,30,120
174,2023-04-12,CUST174,Female,39,Beauty,1,300,300
175,2023-03-20,CUST175,Female,31,Electronics,4,25,100
176,2023-07-11,CUST176,Female,43,Beauty,2,50,100
177,2023-03-24,CUST177,Male,45,Beauty,2,50,100
178,2023-10-04,CUST178,Male,40,Clothing,2,30,60
179,2023-09-29,CUST179,Male,31,Electronics,1,300,300
180,2023-01-01,CUST180,Male,41,Clothing,3,300,900
181,2023-11-03,CUST181,Male,19,Electronics,4,300,1200
182,2023-06-15,CUST182,Male,62,Beauty,4,30,120
183,2023-09-08,CUST183,Female,43,Beauty,3,300,900
184,2023-01-10,CUST184,Male,31,Electronics,4,50,200
185,2023-02-27,CUST185,Male,24,Clothing,1,25,25
186,2023-07-05,CUST186,Male,20,Clothing,4,50,200
187,2023-06-07,CUST187,Female,64,Clothing,2,50,100
188,2023-05-03,CUST188,Male,40,Clothing,3,25,75
189,2023-01-30,CUST189,Male,63,Beauty,1,50,50
190,2023-05-04,CUST190,Female,60,Beauty,3,30,90
191,2023-10-18,CUST191,Male,64,Beauty,1,25,25
192,2023-02-10,CUST192,Male,62,Beauty,2,50,100
193,2023-02-13,CUST193,Male,35,Beauty,3,500,1500
194,2023-09-06,CUST194,Male,55,Clothing,4,50,200
195,2023-02-05,CUST195,Male,52,Clothing,1,30,30
196,2023-09-30,CUST196,Female,32,Clothing,3,300,900
197,2023-03-06,CUST197,Female,42,Clothing,4,50,200
198,2023-03-07,CUST198,Female,54,Beauty,3,300,900
199,2023-12-04,CUST199,Male,45,Beauty,3,500,1500
200,2023-09-01,CUST200,Male,27,Beauty,3,50,150
201,2023-10-09,CUST201,Male,56,Electronics,1,25,25
202,2023-03-26,CUST202,Female,34,Clothing,4,300,1200
203,2023-05-16,CUST203,Male,56,Clothing,2,500,1000
204,2023-09-28,CUST204,Male,39,Beauty,1,25,25
205,2023-11-07,CUST205,Female,43,Clothing,1,25,25
206,2023-08-05,CUST206,Male,61,Clothing,1,25,25
207,2023-04-19,CUST207,Female,42,Beauty,2,25,50
208,2023-10-04,CUST208,Female,34,Electronics,4,50,200
209,2023-12-20,CUST209,Female,30,Electronics,4,50,200
210,2023-04-13,CUST210,Male,37,Electronics,4,50,200
211,2024-01-01,CUST211,Male,42,Beauty,3,500,1500
212,2023-06-09,CUST212,Male,21,Clothing,3,500,1500
213,2023-07-24,CUST213,Male,27,Beauty,3,500,1500
214,2023-12-10,CUST214,Male,20,Beauty,2,30,60
215,2023-11-29,CUST215,Male,58,Clothing,3,500,1500
216,2023-07-11,CUST216,Male,62,Electronics,2,50,100
217,2023-08-13,CUST217,Female,35,Electronics,4,50,200
218,2023-09-22,CUST218,Male,64,Beauty,3,30,90
219,2023-08-20,CUST219,Female,53,Electronics,3,30,90
220,2023-03-03,CUST220,Male,64,Beauty,1,500,500
221,2023-05-07,CUST221,Male,39,Beauty,2,300,600
222,2023-04-26,CUST222,Male,51,Clothing,4,30,120
223,2023-02-02,CUST223,Female,64,Clothing,1,25,25
224,2023-06-23,CUST224,Female,25,Clothing,1,50,50
225,2023-01-11,CUST225,Female,57,Beauty,4,25,100
226,2023-10-29,CUST226,Female,61,Clothing,1,50,50
227,2023-10-11,CUST227,Male,36,Electronics,2,50,100
228,2023-04-28,CUST228,Female,59,Electronics,2,30,60
229,2023-10-29,CUST229,Male,58,Beauty,3,30,90
230,2023-04-23,CUST230,Male,54,Beauty,1,25,25
231,2023-01-04,CUST231,Female,23,Clothing,3,50,150
232,2023-02-06,CUST232,Female,43,Beauty,1,25,25
233,2023-12-29,CUST233,Female,51,Beauty,2,300,600
234,2023-11-20,CUST234,Female,62,Electronics,2,25,50
235,2023-01-31,CUST235,Female,23,Electronics,2,500,1000
236,2023-04-28,CUST236,Female,54,Clothing,1,25,25
237,2023-02-04,CUST237,Female,50,Beauty,2,500,1000
238,2023-01-17,CUST238,Female,39,Beauty,1,500,500
239,2023-06-19,CUST239,Male,38,Electronics,3,500,1500
240,2023-02-06,CUST240,Female,23,Beauty,1,300,300
241,2023-09-21,CUST241,Female,23,Electronics,3,25,75
242,2023-05-02,CUST242,Male,21,Clothing,1,25,25
243,2023-05-23,CUST243,Female,47,Electronics,3,300,900
244,2023-12-09,CUST244,Male,28,Beauty,2,50,100
245,2023-09-06,CUST245,Male,47,Clothing,3,30,90
246,2023-04-20,CUST246,Female,48,Electronics,2,25,50
247,2023-10-04,CUST247,Male,41,Electronics,2,30,60
248,2023-03-09,CUST248,Male,26,Clothing,3,300,900
249,2023-10-20,CUST249,Male,20,Clothing,1,50,50
250,2023-10-23,CUST250,Male,48,Electronics,1,50,50
251,2023-08-31,CUST251,Female,57,Beauty,4,50,200
252,2023-05-05,CUST252,Male,54,Electronics,1,300,300
253,2023-08-31,CUST253,Female,53,Clothing,4,500,2000
254,2023-07-28,CUST254,Male,41,Electronics,1,500,500
255,2023-04-08,CUST255,Male,48,Clothing,1,30,30
256,2023-02-18,CUST256,Male,23,Clothing,2,500,1000
257,2023-02-19,CUST257,Male,19,Beauty,4,500,2000
258,2023-12-04,CUST258,Female,37,Clothing,1,50,50
259,2023-08-09,CUST259,Female,45,Clothing,4,50,200
260,2023-07-01,CUST260,Male,28,Beauty,2,30,60
261,2023-08-05,CUST261,Male,21,Clothing,2,25,50
262,2023-07-30,CUST262,Female,32,Beauty,4,30,120
263,2023-08-28,CUST263,Male,23,Beauty,2,30,60
264,2023-01-28,CUST264,Male,47,Clothing,3,300,900
265,2023-12-11,CUST265,Male,55,Clothing,3,300,900
266,2023-12-01,CUST266,Female,19,Electronics,2,30,60
267,2023-11-27,CUST267,Female,32,Beauty,3,30,90
268,2023-02-20,CUST268,Female,28,Electronics,1,30,30
269,2023-02-01,CUST269,Male,25,Clothing,4,500,2000
270,2023-07-26,CUST270,Male,43,Electronics,1,300,300
271,2023-06-23,CUST271,Female,62,Beauty,4,30,120
272,2023-02-25,CUST272,Female,61,Electronics,2,50,100
273,2023-05-08,CUST273,Female,22,Beauty,1,50,50
274,2023-04-09,CUST274,Female,23,Clothing,2,500,1000
275,2023-04-08,CUST275,Male,43,Clothing,2,500,1000
276,2023-10-02,CUST276,Female,21,Beauty,4,25,100
277,2023-08-18,CUST277,Male,36,Clothing,4,25,100
278,2023-03-13,CUST278,Female,37,Clothing,4,25,100
279,2023-08-05,CUST279,Male,50,Clothing,1,500,500
280,2023-04-04,CUST280,Female,37,Clothing,3,500,1500
281,2023-05-23,CUST281,Female,29,Beauty,4,500,2000
282,2023-08-25,CUST282,Female,64,Electronics,4,50,200
283,2023-05-08,CUST283,Female,18,Electronics,1,500,500
284,2023-02-08,CUST284,Male,43,Clothing,4,50,200
285,2023-08-15,CUST285,Female,31,Electronics,1,25,25
286,2023-10-09,CUST286,Male,55,Electronics,2,25,50
287,2023-02-20,CUST287,Male,54,Clothing,4,25,100
288,2023-01-26,CUST288,Male,28,Clothing,4,30,120
289,2023-11-30,CUST289,Male,53,Electronics,2,30,60
290,2023-10-04,CUST290,Female,30,Beauty,2,300,600
291,2023-01-08,CUST291,Male,60,Clothing,2,300,600
292,2023-02-17,CUST292,Male,20,Beauty,4,300,1200
293,2023-05-02,CUST293,Male,50,Electronics,3,30,90
294,2023-03-27,CUST294,Female,23,Clothing,3,30,90
295,2023-07-28,CUST295,Female,27,Beauty,3,300,900
296,2023-09-06,CUST296,Female,22,Clothing,4,300,1200
297,2023-09-04,CUST297,Female,40,Electronics,2,500,1000
298,2023-04-20,CUST298,Male,27,Beauty,4,300,1200
299,2023-07-25,CUST299,Male,61,Electronics,2,500,1000
300,2023-01-31,CUST300,Female,19,Electronics,4,50,200
301,2023-03-26,CUST301,Male,30,Clothing,4,30,120
302,2023-07-14,CUST302,Male,57,Beauty,2,300,600
303,2023-01-02,CUST303,Male,19,Electronics,3,30,90
304,2023-07-19,CUST304,Female,37,Electronics,2,30,60
305,2023-05-16,CUST305,Female,18,Beauty,1,30,30
306,2023-08-21,CUST306,Male,54,Electronics,1,50,50
307,2023-05-27,CUST307,Female,26,Electronics,2,25,50
308,2023-08-05,CUST308,Female,34,Beauty,4,300,1200
309,2023-12-23,CUST309,Female,26,Beauty,1,25,25
310,2023-10-12,CUST310,Female,28,Beauty,1,25,25
311,2023-12-05,CUST311,Female,32,Beauty,4,25,100
312,2023-09-07,CUST312,Male,41,Clothing,4,30,120
313,2023-03-21,CUST313,Female,55,Beauty,3,500,1500
314,2023-04-08,CUST314,Male,52,Clothing,4,30,120
315,2023-06-01,CUST315,Male,47,Clothing,2,30,60
316,2023-04-22,CUST316,Female,48,Clothing,2,25,50
317,2023-01-30,CUST317,Male,22,Electronics,3,30,90
318,2023-10-24,CUST318,Male,61,Clothing,1,25,25
319,2023-10-05,CUST319,Male,31,Clothing,1,500,500
320,2023-02-01,CUST320,Female,28,Electronics,4,300,1200
321,2023-06-10,CUST321,Female,26,Electronics,2,25,50
322,2023-01-30,CUST322,Male,51,Electronics,1,500,500
323,2023-01-26,CUST323,Female,29,Beauty,3,300,900
324,2023-10-27,CUST324,Female,52,Electronics,3,50,150
325,2023-09-02,CUST325,Female,52,Electronics,2,25,50
326,2023-09-15,CUST326,Female,18,Clothing,3,25,75
327,2023-09-29,CUST327,Male,57,Electronics,3,50,150
328,2023-03-22,CUST328,Male,39,Beauty,2,50,100
329,2023-01-30,CUST329,Female,46,Electronics,4,25,100
330,2023-09-18,CUST330,Female,25,Beauty,4,50,200
331,2023-02-11,CUST331,Male,28,Electronics,3,30,90
332,2023-04-06,CUST332,Male,58,Electronics,4,300,1200
333,2023-02-05,CUST333,Female,54,Electronics,4,300,1200
334,2023-11-01,CUST334,Male,31,Electronics,3,300,900
335,2023-02-04,CUST335,Female,47,Beauty,4,30,120
336,2023-12-12,CUST336,Female,52,Beauty,3,50,150
337,2023-05-01,CUST337,Male,38,Clothing,1,500,500
338,2023-07-26,CUST338,Male,54,Beauty,2,50,100
339,2023-03-03,CUST339,Female,22,Electronics,2,25,50
340,2023-10-19,CUST340,Female,36,Clothing,4,300,1200
341,2023-05-07,CUST341,Male,31,Clothing,4,50,200
342,2023-10-24,CUST342,Female,43,Clothing,4,500,2000
343,2023-11-01,CUST343,Male,21,Electronics,2,25,50
344,2023-01-21,CUST344,Female,42,Beauty,1,30,30
345,2023-11-14,CUST345,Male,62,Electronics,1,30,30
346,2023-02-11,CUST346,Male,59,Clothing,2,500,1000
347,2023-08-03,CUST347,Male,42,Electronics,1,25,25
348,2023-12-03,CUST348,Female,35,Electronics,2,300,600
349,2023-10-26,CUST349,Female,57,Beauty,1,50,50
350,2023-10-17,CUST350,Male,25,Beauty,3,25,75
351,2023-09-25,CUST351,Female,56,Clothing,3,30,90
352,2023-06-11,CUST352,Male,57,Electronics,2,500,1000
353,2023-05-14,CUST353,Male,31,Electronics,1,500,500
354,2023-04-15,CUST354,Female,49,Beauty,4,50,200
355,2023-12-09,CUST355,Female,55,Electronics,1,500,500
356,2023-06-10,CUST356,Male,50,Electronics,3,500,1500
357,2023-05-03,CUST357,Female,40,Electronics,3,25,75
358,2023-05-16,CUST358,Female,32,Beauty,1,300,300
359,2023-07-22,CUST359,Male,50,Clothing,1,50,50
360,2023-03-09,CUST360,Male,42,Clothing,4,25,100
361,2023-12-10,CUST361,Female,34,Electronics,4,300,1200
362,2023-11-27,CUST362,Male,50,Clothing,1,25,25
363,2023-06-03,CUST363,Male,64,Beauty,1,25,25
364,2023-08-23,CUST364,Female,19,Beauty,1,500,500
365,2023-06-11,CUST365,Male,31,Clothing,1,300,300
366,2023-02-07,CUST366,Male,57,Clothing,2,50,100
367,2023-01-05,CUST367,Female,57,Electronics,1,50,50
368,2023-08-23,CUST368,Female,56,Clothing,4,300,1200
369,2023-11-15,CUST369,Male,23,Electronics,3,500,1500
370,2023-10-16,CUST370,Male,23,Electronics,2,30,60
371,2023-02-21,CUST371,Female,20,Beauty,1,25,25
372,2023-02-07,CUST372,Female,24,Beauty,3,500,1500
373,2023-10-03,CUST373,Female,25,Beauty,2,300,600
374,2023-04-20,CUST374,Female,59,Beauty,3,25,75
375,2023-09-17,CUST375,Male,32,Clothing,1,50,50
376,2023-05-16,CUST376,Female,64,Beauty,1,30,30
377,2023-03-09,CUST377,Female,46,Clothing,4,50,200
378,2023-06-28,CUST378,Male,50,Beauty,1,300,300
379,2023-02-05,CUST379,Female,47,Clothing,1,25,25
380,2023-05-06,CUST380,Male,56,Electronics,2,300,600
381,2023-07-09,CUST381,Female,44,Clothing,4,25,100
382,2023-05-26,CUST382,Female,53,Clothing,2,500,1000
383,2023-03-22,CUST383,Female,46,Beauty,3,30,90
384,2023-08-13,CUST384,Male,55,Clothing,1,500,500
385,2023-10-06,CUST385,Male,50,Electronics,3,500,1500
386,2023-12-27,CUST386,Female,54,Electronics,2,300,600
387,2023-06-04,CUST387,Male,44,Beauty,1,30,30
388,2023-11-10,CUST388,Male,50,Electronics,1,25,25
389,2023-12-01,CUST389,Male,21,Clothing,2,25,50
390,2023-09-28,CUST390,Male,39,Electronics,2,50,100
391,2023-01-05,CUST391,Male,19,Beauty,2,25,50
392,2023-12-08,CUST392,Male,27,Clothing,2,300,600
393,2023-10-11,CUST393,Female,22,Beauty,2,500,1000
394,2023-06-03,CUST394,Female,27,Clothing,1,500,500
395,2023-12-06,CUST395,Male,50,Electronics,2,500,1000

In [0]:
# Printing the entire dataset to the console
print(rs)

     Transaction ID        Date  ... Price per Unit Total Amount
0                 1  2023-11-24  ...             50          150
1                 2  2023-02-27  ...            500         1000
2                 3  2023-01-13  ...             30           30
3                 4  2023-05-21  ...            500          500
4                 5  2023-05-06  ...             50          100
..              ...         ...  ...            ...          ...
995             996  2023-05-16  ...             50           50
996             997  2023-11-17  ...             30           90
997             998  2023-10-29  ...             25          100
998             999  2023-12-05  ...             50          150
999            1000  2023-04-12  ...             30          120

[1000 rows x 9 columns]

In [0]:
# Showing the first 5 rows of the dataset
rs.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
#Showing the last 5 rows of the dataset
rs.tail()

     Transaction ID        Date  ... Price per Unit Total Amount
995             996  2023-05-16  ...             50           50
996             997  2023-11-17  ...             30           90
997             998  2023-10-29  ...             25          100
998             999  2023-12-05  ...             50          150
999            1000  2023-04-12  ...             30          120

[5 rows x 9 columns]

In [0]:
# Counting duplicate rows in the dataset
rs.duplicated().sum()

np.int64(0)

In [0]:
# deleting rows with missing values
rs=rs.dropna()

In [0]:
# replacing the missing values with zero
rs=rs.fillna(0)

In [0]:
# Checking for missing (null) values in each column
rs.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [0]:
# Getting the shape of the dataset
rs.shape

(1000, 9)

In [0]:
# checking data types
rs.dtypes

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [0]:
for col in rs.columns:
    print(f"{col}: {rs[col].nunique()} unique values")

Transaction ID: 1000 unique values
Date: 345 unique values
Customer ID: 1000 unique values
Gender: 2 unique values
Age: 47 unique values
Product Category: 3 unique values
Quantity: 4 unique values
Price per Unit: 5 unique values
Total Amount: 18 unique values

In [0]:
corr = rs.corr(numeric_only=True)

In [0]:
rs['Total Amount'].sum()

np.int64(456000)

In [0]:
rs.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False)

Product Category
Electronics    156905
Clothing       155580
Beauty         143515
Name: Total Amount, dtype: int64

In [0]:
rs[rs['Age'] < 30].groupby('Product Category')['Total Amount'].sum()

Product Category
Beauty         41400
Clothing       46150
Electronics    35605
Name: Total Amount, dtype: int64

In [0]:
rs.groupby('Gender')['Total Amount'].sum()

Gender
Female    232840
Male      223160
Name: Total Amount, dtype: int64